const std = @import("std");
const sql_parser = @import("sql_parser.zig");

/// Configuration for code generation.
pub const Config = struct {
    allocator: std.mem.Allocator,
    output_dir: []const u8,
    package_name: []const u8 = "schema",
};

/// Code generator from parsed SQL tables to Zig schema.
pub const Generator = struct {
    config: Config,
    tables: []const sql_parser.Table,

    pub fn init(config: Config, tables: []const sql_parser.Table) Generator {
        return .{
            .config = config,
            .tables = tables,
        };
    }

    /// Generate all schema files.
    pub fn generate(self: *Generator) !void {
        try std.fs.cwd().makePath(self.config.output_dir);

        for (self.tables) |table| {
            try self.generateTableSchema(table);
        }

        try self.generateModFile();
    }

    /// Generate a single table schema file.
    fn generateTableSchema(self: *Generator, table: sql_parser.Table) !void {
        const file_name = try std.fmt.allocPrint(self.config.allocator, "{s}.zig", .{
            std.mem.span(table.name),
        });
        defer self.config.allocator.free(file_name);

        const file_path = try std.fs.path.join(self.config.allocator, &.{
            self.config.output_dir,
            file_name,
        });
        defer self.config.allocator.free(file_path);

        const file = try std.fs.cwd().createFile(file_path, .{});
        defer file.close();

        const writer = file.writer();
        try writer.print(
            \\const zent = @import("zent");
            \\const field = zent.core.field;
            \\const edge = zent.core.edge;
            \\const Schema = zent.core.schema.Schema;
            \\
            \\pub const {s} = Schema("{s}", .{{
            \\    .fields = &.{{
        , .{
            std.mem.span(table.name),
            std.mem.span(table.name),
        });

        for (table.columns.items, 0..) |column, i| {
            const zig_field = try self.sqlTypeToZigField(column);
            try writer.print("        {s}", .{zig_field});
            if (i < table.columns.items.len - 1) {
                try writer.writeAll(",");
            }
            try writer.writeAll("\n");
        }

        try writer.writeAll(
            \\    },
            \\});
            \\
        );
    }

    /// Convert SQL column to Zig field definition.
    fn sqlTypeToZigField(self: *Generator, column: sql_parser.Column) ![]const u8 {
        _ = self;

        var buf = std.ArrayList(u8).init(std.heap.page_allocator);
        defer buf.deinit();

        try buf.writer().print("field.{s}(\"{s}\")", .{
            try sqlTypeToZigType(column.sql_type),
            column.name,
        });

        if (column.primary_key) {
            try buf.appendSlice(".PrimaryKey()");
        }
        if (column.auto_increment) {
            try buf.appendSlice(".AutoIncrement()");
        }
        if (column.not_null) {
            try buf.appendSlice(".Required()");
        } else {
            try buf.appendSlice(".Optional()");
        }
        if (column.default) |default_val| {
            try buf.writer().print(".Default({s})", .{default_val});
        }

        return try buf.toOwnedSlice();
    }

    /// Map SQL type to Zig field type.
    fn sqlTypeToZigType(sql_type: []const u8) ![]const u8 {
        const upper = std.ascii.upperString(sql_type);

        if (std.mem.indexOf(upper, "INT") != null) {
            return "Int";
        } else if (std.mem.indexOf(upper, "TEXT") != null or
            std.mem.indexOf(upper, "CHAR") != null or
            std.mem.indexOf(upper, "VARCHAR") != null)
        {
            return "String";
        } else if (std.mem.indexOf(upper, "REAL") != null or
            std.mem.indexOf(upper, "FLOAT") != null or
            std.mem.indexOf(upper, "DOUBLE") != null)
        {
            return "Float";
        } else if (std.mem.indexOf(upper, "BOOL") != null or
            std.mem.indexOf(upper, "BOOLEAN") != null)
        {
            return "Bool";
        } else if (std.mem.indexOf(upper, "TIME") != null or
            std.mem.indexOf(upper, "DATE") != null)
        {
            return "Time";
        } else if (std.mem.indexOf(upper, "BLOB") != null or
            std.mem.indexOf(upper, "BYTEA") != null)
        {
            return "Bytes";
        } else if (std.mem.indexOf(upper, "JSON") != null) {
            return "JSON";
        }

        return "String";
    }

    /// Generate the module file that exports all schemas.
    fn generateModFile(self: *Generator) !void {
        const file_path = try std.fs.path.join(self.config.allocator, &.{
            self.config.output_dir,
            "mod.zig",
        });
        defer self.config.allocator.free(file_path);

        const file = try std.fs.cwd().createFile(file_path, .{});
        defer file.close();

        const writer = file.writer();
        try writer.writeAll(
            \\// Auto-generated by zent CLI
            \\// Do not edit manually
            \\
        );

        for (self.tables) |table| {
            try writer.print("pub const {s} = @import(\"{s}.zig\");\n", .{
                std.mem.span(table.name),
                std.mem.span(table.name),
            });
        }
    }
};

test "Basic code generation structure" {
    const allocator = std.testing.allocator;
    
    // Just test that the types are accessible
    _ = Config{
        .allocator = allocator,
        .output_dir = "./test",
    };
}
